### DISCUSSION TITLE
Inference

### DISCUSSION THREAD

**Discussion by jywu-hiphen** [hysts/pytorch_image_classification#26] [Q&A]
Hello - thanks and great work!

I'm struggling to get my head around `evaluate.py` would you have an example of `config` line for it ? Is it what we should use for inference once we've saved our `.pth` file ?

Many thanks,
Joss

**Comment by hysts** [comment]
Hi, @jywu-hiphen 

I added [a sample notebook](https://github.com/hysts/pytorch_image_classification/blob/master/notebooks/demo.ipynb) for the inference. Take a look at it.

As for `evaluate.py`, it only works with the CIFAR datasets, so it might not be that useful.
But anyway, if you want to use it, you can use the config file you used for training if you specify `test.checkpoint` and `test.output_dir`.
For example, in case of `configs/cifar/resnet.yaml`, if you add the following lines to it, you can run `evaluate.py` with it:
```yaml
test:
  checkpoint: experiments/cifar10/resnet/exp00/checkpoint_00160.pth
  output_dir: experiments/cifar10/resnet/exp00/pred_00160
```
